export const localDict = {
    A: "BLUK",
    B: "BUL",
    C: "BULK",
    D: "BLUB",
    E: "BLUKBLUK",
    F: "BLUKBUL",
    G: "BLUKBULK",
    H: "BLUKBLUB",
    I: "BULBLUK",
    J: "BULBUL",
    K: "BULBULK",
    L: "BULBLUB",
    M: "BULKBLUK",
    N: "BULKBUL",
    O: "BULKBULK",
    P: "BULKBLUB",
    Q: "BLUBBLUK",
    R: "BLUBBUL",
    S: "BLUBBULK",
    T: "BLUBBLUB",
    U: "BLUKBLUKBLUK",
    V: "BLUKBLUKBUL",
    W: "BLUKBLUKBULK",
    X: "BLUKBLUKBLUB",
    Y: "BLUKBULBLUK",
    Z: "BLUKBULBUL",
    " ": "|",
}

export const cupangDict = {
    BLUK: "A",
    BUL: "B",
    BULK: "C",
    BLUB: "D",
    BLUKBLUK: "E",
    BLUKBUL: "F",
    BLUKBULK: "G",
    BLUKBLUB: "H",
    BULBLUK: "I",
    BULBUL: "J",
    BULBULK: "K",
    BULBLUB: "L",
    BULKBLUK: "M",
    BULKBUL: "N",
    BULKBULK: "O",
    BULKBLUB: "P",
    BLUBBLUK: "Q",
    BLUBBUL: "R",
    BLUBBULK: "S",
    BLUBBLUB: "T",
    BLUKBLUKBLUK: "U",
    BLUKBLUKBUL: "V",
    BLUKBLUKBULK: "W",
    BLUKBLUKBLUB: "X",
    BLUKBULBLUK: "Y",
    BLUKBULBUL: "Z",
    "|": " ",
}
